
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MO = 23;
  public static final int IDwithUnder = 18;
  public static final int PO = 24;
  public static final int COMP_OP = 15;
  public static final int AA = 35;
  public static final int SM = 7;
  public static final int DB = 26;
  public static final int COMMENTS = 14;
  public static final int LOG_OP = 16;
  public static final int Under = 17;
  public static final int INTEGER = 20;
  public static final int MB = 25;
  public static final int Func = 12;
  public static final int LT = 27;
  public static final int CM = 38;
  public static final int LS = 36;
  public static final int CL = 5;
  public static final int DETENT = 3;
  public static final int LP = 32;
  public static final int RS = 37;
  public static final int BOOL = 4;
  public static final int CLASS = 9;
  public static final int LOOP = 11;
  public static final int FOUR_TAB = 6;
  public static final int FA = 34;
  public static final int EOF = 0;
  public static final int LC = 30;
  public static final int SYSTEM = 10;
  public static final int KEYWORD = 8;
  public static final int error = 1;
  public static final int RC = 31;
  public static final int RB = 33;
  public static final int FULL_COMMENT = 13;
  public static final int NUMBER = 19;
  public static final int EQ = 29;
  public static final int STRING = 21;
  public static final int GT = 28;
  public static final int AO = 2;
  public static final int DO = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AO",
  "DETENT",
  "BOOL",
  "CL",
  "FOUR_TAB",
  "SM",
  "KEYWORD",
  "CLASS",
  "SYSTEM",
  "LOOP",
  "Func",
  "FULL_COMMENT",
  "COMMENTS",
  "COMP_OP",
  "LOG_OP",
  "Under",
  "IDwithUnder",
  "NUMBER",
  "INTEGER",
  "STRING",
  "DO",
  "MO",
  "PO",
  "MB",
  "DB",
  "LT",
  "GT",
  "EQ",
  "LC",
  "RC",
  "LP",
  "RB",
  "FA",
  "AA",
  "LS",
  "RS",
  "CM"
  };
}

